package integration

import (
	"bytes"
	"context"
	"embed"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/ldebello/wt/internal/config"
)

//go:embed templates/*.md
var builtinTemplates embed.FS

// Marker is the first line of every generated file. wt only overwrites or
// deletes files that still contain it.
const Marker = "<!-- Generated by wt. Delete this line to keep your edits: wt will stop regenerating this file. -->"

// HarnessNames are the supported harnesses.
var HarnessNames = []string{"claude", "generic"}

var harnessDefaults = map[string]struct{ file, template string }{
	"claude":  {file: "CLAUDE.md", template: "claude"},
	"generic": {file: "AGENTS.md", template: "agents"},
}

// Harness writes an AI agent instruction file (CLAUDE.md, AGENTS.md, ...) at
// the workspace root from a Go template.
type Harness struct {
	name      string
	enabled   bool
	file      string
	template  string
	wtHome    string
	codegraph bool
}

// NewHarness builds harness name ("claude" or "generic") from its settings.
func NewHarness(name string, cfg config.Harness, wtHome string, codegraph bool) *Harness {
	d := harnessDefaults[name]
	h := &Harness{name: name, enabled: cfg.Enabled, file: d.file, template: cfg.Template, wtHome: wtHome, codegraph: codegraph}
	if h.template == "" {
		h.template = d.template
	}
	return h
}

func (h *Harness) Name() string  { return "harness " + h.name }
func (h *Harness) Enabled() bool { return h.enabled }

// File is the generated file name.
func (h *Harness) File() string { return h.file }

func (h *Harness) Check() error {
	if h.file == "" {
		return fmt.Errorf("unknown harness %q (use claude or generic)", h.name)
	}
	_, err := h.load()
	return err
}

func (h *Harness) Setup(ctx context.Context) error { return h.Check() }

// load reads ~/.wt/templates/<template>.md, falling back to the built-in one.
func (h *Harness) load() (*template.Template, error) {
	name := h.template + ".md"
	data, err := os.ReadFile(filepath.Join(h.wtHome, "templates", name))
	if errors.Is(err, os.ErrNotExist) {
		data, err = builtinTemplates.ReadFile("templates/" + name)
		if err != nil {
			return nil, fmt.Errorf("harness %s: template %q not found in %s or built in", h.name, h.template, filepath.Join(h.wtHome, "templates"))
		}
	}
	if err != nil {
		return nil, err
	}
	tmpl, err := template.New(name).Parse(string(data))
	if err != nil {
		return nil, fmt.Errorf("harness %s: %w", h.name, err)
	}
	return tmpl, nil
}

// templateData is what templates can reference.
type templateData struct {
	Workspace
	Codegraph bool
}

func (h *Harness) OnWorkspaceCreated(ctx context.Context, ws Workspace) error {
	path := filepath.Join(ws.Path, h.file)
	if existing, err := os.ReadFile(path); err == nil && !bytes.Contains(existing, []byte(Marker)) {
		return nil // edited by the user
	}
	tmpl, err := h.load()
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	buf.WriteString(Marker + "\n")
	if err := tmpl.Execute(&buf, templateData{Workspace: ws, Codegraph: h.codegraph}); err != nil {
		return fmt.Errorf("harness %s: %w", h.name, err)
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func (h *Harness) OnWorkspaceRemoved(ctx context.Context, ws Workspace) error {
	path := filepath.Join(ws.Path, h.file)
	data, err := os.ReadFile(path)
	if err != nil || !strings.Contains(string(data), Marker) {
		return nil
	}
	return os.Remove(path)
}
